### ISSUE TITLE
Error: Cannot find module 'push-app'

### ISSUE THREAD

**Issue by brendandahl** [sole/install-to-adb#1]
You may want to mention in the readme you also need to manually install push-app as well.

BTW, nice module, I'm finding it quite a bit less painful than webide.

**Comment by sole** [comment]
Sorry I didn't see this issue before! OMG github notifications failed me again
I think it was due to an error on my side because I didn't add that module to package.json
It should be fixed now, push-app is installed now when you do npm install :-)
