### ISSUE TITLE
Cannot bind to socket

### ISSUE THREAD

**Issue by johanpoirier** [sole/install-to-adb#2]
When I try to push my app to my devices, I always get a `Unhandled rejection FailError: Failure: 'cannot bind to socket'`

The same thing happens with the demo.js script.

**Comment by sole** [comment]
Interesting! What setup do you have? Did you root your phone and enabled all the things you have to enable? e.g. ADB+Devtools debugging?

**Comment by johanpoirier** [comment]
I have a Flame, and debugging is set to ADB and DevTools.
I'm using install-to-adb on a MacBook Air running OS X 10.10.2.

The Flame is rooted by default, isn't it?

**Comment by johanpoirier** [comment]
I just flashed my Flame to Firefox 3.0 and then back to 2.0 and it works fine now (with both versions).

Thanks anyway, this is a great little module.
